from src.algo.algo import Algo
from src.algo.fedbase import FedBase
from src.algo.fedavg import FedAvg
from src.algo.fedseq import FedSeq
from src.algo.centralized import Centralized
from src.algo.fedseq_inter import FedSeqInter
from src.algo.scaffold import SCAFFOLD
from src.algo.fedseq_scaffold import FedSeqSCAFFOLD
from src.algo.fedseq_loss_tracking import FedSeqLossTracking