defaults:
  - model: soverflow
  - algo: fedavg
  - dataset: soverflow_niid
  - _self_

n_round: 100
device: 'cpu'

seed: 2021
output_suffix: ""
do_train: True
test_on_data: 
  dataset: null
  model: fedseq-thesis/test-project/y5j6jsug/models/model_r6.pt
 #null, {run_path}/models/{model_name} e.g.run_path=fedseq-thesis/test-project/1evvle06

root: ${oc.env:PWD}
savedir: ${oc.env:PWD}/output/${algo.type}/${now:%Y-%m-%d_%H-%M-%S}

wandb:
  restart_from_run: null #run_id/null
  run_suffix: 2 #null/n.times this run is being repeated
  entity: "fedseq-thesis"
  tags: ["federated comparison"]
  server_model:
    save_every_n_rounds: False
    tot_round: 2
  client_datasets: true # true/false
  superclient_datasets: true #true/false



hydra:
  run:
    dir: ${oc.env:PWD}/output/${algo.type}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    # Output directory for sweep runs
    dir: ${oc.env:PWD}/output/${algo.type}/${now:%Y-%m-%d_%H-%M-%S}/${hydra.job.name}
    # Output sub directory for sweep runs.
    subdir: ${hydra.job.num}_${hydra.job.id}
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}${output_suffix}.log
