# @package _global_
defaults:
  - fedavg

algo:
  type: fedavg_GAN_attack
  classname: FedAvgGANattack
  params:
    GAN_train_epochs: 300
    GAN_n_fake_images: 5000
    GAN_save_after_n_rounds: 100
    output_folder: '/home/arizzardi/FedAvg_GAN_attack_bigReconstruction'
    save_attacker: True
    save_dataset_explicit: True
    save_images: False
    save_loss: False
    save_dataset_per_client: True
    save_client_selection: True
    save_client_distribution: True
    save_accuracy: True