# @package _global_
defaults:
  - fedbase
  - optim@algo.params: sgd
  - loss@algo.params: crossentropy

algo:
  type: fedavg
  classname: FedAvg
  params:
    optim:
      args:
        momentum: 0
    center_server:
      classname: LayerPermCenterServer
    client:
      classname: FedAvgClient
      args: {}
    aggregation_policy: weighted