# @package _global_
defaults:
  - fedseq_parallel

algo:
  type: fedseq_dyn_gsp
  params:
    alpha: 0.1
    center_server:
      classname: FedDynCenterServer
      args:
        num_clients: ${algo.params.common.K}
        alpha: ${algo.params.alpha}
    client:
      classname: FedDynClient
      args:
        alpha: ${algo.params.alpha}