# @package _global_
defaults:
  - fedseq

algo:
  type: fedseq_asam
  classname: FedSeqASAM
  params:
    eta: 0
    rho: 0.01
    lr2: 0.0001 #gamma2 a γ2 = 10−4
    c: 10 #The cycle length c is tested in {5, 10, 20} and set to 10 for Cifar10 and 20 for Cifar100.
    swa_start: 0.9
    adaptive: False
    center_server:
      classname: FedSWACenterServer
      args:
        swa_start: ${algo.params.swa_start}
        c: ${algo.params.c}
        tot_epochs : ${n_round}
    client:
      classname: ASAMClient
      args:
        eta: ${algo.params.eta}
        rho: ${algo.params.rho}
        adaptive: ${algo.params.adaptive}