# @package _global_
defaults:
  - fedseq

algo:
  type: fedseq_parallel
  classname: FedSeqToParallel
  params:
    growth_func: log
    alpha_growth: 2
    beta_growth: 50
    keep_representers: True