# @package _global_

defaults:
  - fedavg
  - optim@algo.params.evaluator: sgd

algo:
  type: fedseq
  classname: FedSeq
  params:
    clustering:
      classnames_eval: [] # for these save_statistics is True
      measures_eval: []
      disomogeneity_measures: ["gini", "kullback"] #measures that apply only to probability distributions
      classname: RandomClusterMaker
      max_clients: 5
      min_examples: 400
      measure: cosine
      save_statistics: False
      verbose: False
    evaluator:
      extract_eval : []
      epochs: 10
      extract: "classifierLast" # classifierAll classifierLast or classifierLast2 or confidence or classifierAll
      extract_prop_distr: ["confidence"] #methods that extract probability distributions
      variance_explained: 0.9 #percentage of variance explained
    training:
      average_model: False
      sequential_rounds: 1 #number of sequential iterations through superclients' clients
      clients_local_epoch: ${algo.params.common.E} # number of local iteration for each client
      check_forgetting: False
      shuffle_sp_clients: True
      clients_dropout: ${algo.params.clients_dropout}
    save_models: False
    common:
      dp: #differential privacy
