# @package _global_
defaults:
  - fedseq

algo:
  type: fedseq_labelFlipping_attack
  classname: FedSeqLabelFlippingAttack
  params:
    percentage_superclient_infected: 0.5
    percentage_client_infected_in_superclient: 1.0
    scramble_method: "random" #random vs fixed
    scrambled_classes : [3,5,0,2]

