# @package _global_
defaults:
  - fedseq

algo:
  type: fedseq_GAN_attack
  classname: FedSeqGANattack
  params:
    output_folder: '/home/arizzardi/FedSeq_ExplicitCifar'
    save_dataset_explicit: True
    save_images: False
    save_loss: False
    
