# @package _global_

defaults:
  - fedavg
  - optim@algo.params.evaluator: sgd

algo:
  type: fedseq
  classname: FedSeq
  params:
    clustering:
      precomputed: null #path to superclients or null
      classnames_eval: [] # for these save_statistics is True
      measures_eval: []
      disomogeneity_measures: ["gini", "kullback"] #measures that apply only to probability distributions
      classname: GreedyClusterMaker
      max_clients: 11
      min_examples: 800
      measure: cosine
      save_statistics: False
      verbose: False
    evaluator:
      precomputed: null #path to representers or null
      extract_eval : []
      epochs: 10
      extract: "confidence" # classifierAll classifierLast or classifierLast2 or confidence or classifierAll
      extract_prop_distr: ["confidence"] #methods that extract probability distributions
      variance_explained: 0.9 #percentage of variance explained
      task2vec:
        method: 'montecarlo' #either variational or montecarlo method
        probe_network: 'resnet18' #either resnet18 or resnet34 for now
    training:
      average_model: False
      sequential_rounds: 1 #number of sequential iterations through superclients' clients
      clients_local_epoch: ${algo.params.common.E} # number of local iteration for each client
      check_forgetting: False
      shuffle_sp_clients: True
      clients_dropout: ${algo.params.clients_dropout}
    save_models: False
    save_representers: False
    save_superclients: False
    save_plot_dist_matrix: True
    common:
      dp: #differential privacy
