name: cifar10
dataset_class: CifarLocalDataset
dataset_num_class: 10
dataset_size: 50000
num_exemplar: 100
average_accuracy_rounds: 100
accuracy_centralized: 85.72 
percentages_saved: [0.7, 0.8, 0.9]
params:
  max_iter_dirichlet: 100
  rebalance: False
  shuffle_start_index: True #shuffles starting index for niid
