name: cifar10
dataset_class: CifarLocalDataset
dataset_num_class: 10
dataset_size: 50000
num_exemplar: 100
average_accuracy_rounds: 2
accuracy_centralized: null 
percentages_saved: [0.7, 0.8, 0.9]
params:
  max_iter_dirichlet: 100
  rebalance: False
