name: emnist_niid_subset
dataset_class: EmnistLocalDataset
dataset_num_class: 62
dataset_size: 70646 #test size:81722
num_exemplar: 82
average_accuracy_rounds: 25
accuracy_centralized: null 
percentages_saved: [0.7, 0.8, 0.9]
params:
