name: emnist_iid
dataset_class: ShakespeareLocalDataset
dataset_num_class: 62
dataset_size: to_do
num_exemplar: to_do
average_accuracy_rounds: 100
accuracy_centralized: null 
percentages_saved: [0.7, 0.8, 0.9]
params:
