name: soverflow_niid
dataset_class: StackoverflowLocalDataset
dataset_num_class: 10004
dataset_size: 135818730
num_exemplar: 165860
average_accuracy_rounds: 100
accuracy_centralized: null
percentages_saved: [0.7, 0.8, 0.9]
params:
